{{- if .Values.collabServer.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "excalidraw.fullname" . }}-collab
  labels:
    {{- include "excalidraw.labels-collab" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "excalidraw.selectorLabels-collab" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.collabServer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "excalidraw.selectorLabels-collab" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "excalidraw.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.collabServer.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-collab
          securityContext:
            {{- toYaml .Values.collabServer.securityContext | nindent 12 }}
          image: "{{ .Values.collabServer.image.repository }}:{{ .Values.collabServer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.collabServer.image.pullPolicy }}
          ports:
            - name: ws
              containerPort: 3002
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: ws
          readinessProbe:
            tcpSocket:
              port: ws
          resources:
            {{- toYaml .Values.collabServer.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
